"""Реплики на местах, акты 1–3 — design/banter/02_places.md, согласовано 2026-09-26.

Каждое место — AD (реплика над головой, без остановки игры), звучит один раз за игру, когда
Альфира в активном отряде. Варианты — по приоритету 💞 > ✨ > ❄️ > обычный (флаги настроения,
ads.MOOD). Механизм — scripts/dialogs/ads.py и goal ALFSV_World.txt (генерируется).

Откуда запуск (всё — по данным игры, файл:строка в source):
  * triggers — EnteredTrigger(Альфира, триггер). Берём только триггеры, которые игра сама держит
    зарегистрированными для отряда: подрегионы (DB_Subregion / DB_SubregionMarker →
    _GLOBAL_Subregions.txt: PROC_TriggerRegisterForParty), триггеры бесед отряда
    (PROC_RegisterWorldGossipTrigger → GLO_WorldGossip.txt:59, не снимаются) и т. п. Свою регистрацию
    мод не делает: иначе у чужих правил EnteredTrigger на тех же триггерах появились бы события,
    которых игра не ждёт;
  * flags — глобальный флаг игры (FlagSet); levels — начало уровня (LevelGameplayStarted);
  * custom — особый запуск (фуникулёр Яслей: три реплики по ходу рейса, ads.LIFT_BLOCK).
Места без надёжного триггера — в GAPS (реплики остаются в сценарии, в игру не идут).
"""
from ads import COLD, NOTCH, ROMANCE, SPARK, place, variant
from dsl import say, voice

G1 = "Gustav/Mods/Gustav/Story/RawFiles/Goals/"
GD = "Gustav/Mods/GustavDev/Story/RawFiles/Goals/"

PLACES = [
    # ---------------------------------------------------------------- Акт 1
    # ⭐ Фуникулёр в Яслях Иллек — сцена из трёх реплик
    place("CRE_LiftStart", "Ясли Иллек: фуникулёр, начало подъёма",
          variant(say("Gith architecture: beautiful, terrifying, and not a single handrail.",
                      "Зодчество гитьянки: красиво, жутко и ни одного поручня.", emo="surprise>happy")),
          act=1, custom="lift", source=GD + "Act1b_CRE_Exterior.txt:103-119,190-202 (PROC_CRE_Dungeon_ElevatorMove)"),
    place("CRE_LiftMid", "Ясли Иллек: фуникулёр, середина пути",
          variant(say("Stand closer. For balance. *My* balance.", "Встань поближе. Для равновесия. *Моего* равновесия.",
                      emo="happy/2"), when=[ROMANCE]),
          variant(say("I'm going to remember this. Not the gith. Not the rock. This. You, standing there.",
                      "Я это запомню. Не гитьянки. Не камень. Вот это. Тебя, вот так.", emo="thinking>happy",
                      note="(не отрывая глаз от вида)"), when=[SPARK]),
          variant(say("...It's pretty. I'll give it that.", "…Красиво. Этого не отнять.", emo="neutral"), when=[COLD]),
          variant(say("Look - the whole valley. We're riding a *rock* through the *sky*. Lihala, you'd have *screamed*.",
                      "Смотри — вся долина. Мы едем на *камне* по *небу*. Лихейла, ты бы *визжала*.",
                      emo="surprise>happy/2")),
          act=1, custom="lift", source=GD + "Act1b_CRE_Exterior.txt (опрос расстояния до точки назначения)"),
    place("CRE_LiftTop", "Ясли Иллек: фуникулёр, наверху",
          variant(say("There's a verse in this. Wind, stone, and nobody saying a word. I'll find it.",
                      "Здесь есть куплет. Ветер, камень и тишина. Я его найду.", emo="thinking>happy")),
          act=1, custom="lift", source=GD + "Act1b_CRE_Exterior.txt:204-211 (PlatformMovementFinished)"),

    place("MountainPass", "Горный перевал, вид на долину",
          variant(say("Is that - is that the whole Sword Coast? Lihala would've climbed that rock just to shout at it.",
                      "Это что… всё Побережье Мечей? Лихейла залезла бы на тот камень, просто чтобы на него покричать.",
                      emo="surprise>happy")),
          act=1, triggers=["S_PLA_MountainPass_SUB_e0daf9ba-4b75-4482-b73a-b46fc8f62a44"],
          source=G1 + "Act1_Subregions.txt (DB_Subregion PLA_MountainPass_SUB)"),
    place("Monastery", "Обитель Розиморн",
          variant(say("Monks lived here once. Chanting all day. I bet the echo was *glorious*.",
                      "Когда-то здесь жили монахи. Пели целыми днями. Готова спорить, эхо было *великолепным*.",
                      emo="thinking>happy")),
          act=1, triggers=["S_CRE_Monastery_SUB_94be6628-ed02-4bdc-9173-5d1b06f26daa"],
          source=GD + "Act1b_Subregions.txt (CRE_Monastery_SUB)"),
    place("UnderdarkFirst", "Подземье, первый шаг",
          variant(say("No sky, no stars - how do you even *write* down here?",
                      "Ни неба, ни звёзд — как тут вообще можно *сочинять*?", emo="fear>thinking")),
          act=1, triggers=["S_UND_Underdark_SUB_b379a862-a59f-4e52-9166-23fbe0e8976e"],
          source=G1 + "Act1_Subregions.txt (UND_Underdark_SUB)"),
    place("Myconids", "Подземье, колония миконидов",
          variant(say("It's like the whole cave is humming a note I can't quite hear.",
                      "Будто вся пещера тянет ноту, которую я никак не расслышу.", emo="thinking")),
          act=1, triggers=["S_UND_MyconidCircle_SUB_4b5cc8fc-88f4-465e-bf82-4c20b055c019"],
          source=G1 + "Act1_Subregions.txt:54 (UND_MyconidCircle_SUB)"),
    place("AdamantineForge", "Адамантиновая кузня",
          variant(say("Listen. The whole forge keeps time. *Boom* - two, three - *boom*.",
                      "Слушай. Вся кузня держит ритм. *Бум* — два, три — *бум*.", emo="surprise>happy")),
          act=1, triggers=["S_UND_AdamantineForge_SUB_5fd81ed1-b91b-413e-91de-360715aba962"],
          source=G1 + "Act1_Subregions.txt (UND_AdamantineForge_SUB)"),
    place("SacredPool", "Изумрудная роща, Священный пруд",
          variant(say("The only place in the Grove that doesn't sound afraid.",
                      "Единственное место в Роще, которое не звучит испуганно.", emo="thinking>happy")),
          act=1, triggers=["S_DEN_SacredPond_SUB_2303e19f-549f-434f-bee0-b886fb34c46a"],
          source=G1 + "Act1_Subregions.txt:18 (DEN_SacredPond_SUB)"),
    place("RisenRoad", "Всхожая дорога",
          variant(say("We came this way. ...Can we walk a bit faster?", "Мы шли этой дорогой. …Можно чуть быстрее?",
                      emo="sad>fear", note="(тихо)")),
          act=1, triggers=["S_PLA_Plains_SUB_bcc3efa5-bfe1-4224-9df1-6758cac764cd"],
          source=G1 + "Act1_Subregions.txt:45 (PLA_Plains_SUB) — [проверить в игре: подрегион «равнин» = Всхожая дорога]"),
    place("BlightedVillage", "Вымершая деревня",
          variant(say("Someone sang here, I bet. Badly, probably. Everyone sings badly at home.",
                      "Здесь кто-то пел, готова спорить. Наверное, плохо. Дома все поют плохо.", emo="sad>happy")),
          act=1, triggers=["S_FOR_ForestVillage_SUB_21e6bfbf-c5c9-4e99-97f8-2df7143967c4"],
          source=G1 + "Act1_Subregions.txt:30 (FOR_ForestVillage_SUB)"),
    place("CrashSite", "Место крушения наутилоида",
          variant(say("So that's what fell out of the sky. I've written songs about less.",
                      "Так вот что упало с неба. Я писала песни и о меньшем.", emo="surprise>happy")),
          act=1, triggers=["S_CRA_Beach_SUB_a78bd6f2-9c61-4866-a6d7-74a46ebd82b0"],
          source=G1 + "Act1_Subregions.txt:85 (CRA_Beach_SUB)"),
    place("Teahouse", "Чайный домик у реки",
          variant(say("Nobody sets out that many cakes without wanting something.",
                      "Никто не выставляет столько пирожных просто так.", emo="thinking")),
          act=1, triggers=["S_HAG_House_SUB_a54033ab-fc50-476b-99c6-5d6ad01bcf18"],
          source=G1 + "Act1_HAG_Hag.txt:74 (DB_SubregionMarker HAG_HagHouse_SUB)"),
    place("GoblinCamp", "Лагерь гоблинов",
          variant(say("Walk normally. Walk *normally*. We're just... visiting.",
                      "Иди как обычно. Как *обычно*. Мы просто… в гостях.", emo="fear>happy")),
          act=1, triggers=["S_GOB_Festivities_SUB_217424e5-f9b7-4441-ab09-715076696a12"],
          source=G1 + "Act1_Subregions.txt (GOB_Festivities_SUB) — [проверить в игре: двор лагеря у Разрушенного святилища]"),
    place("DankCrypt", "Темный склеп",
          variant(voice("he4532a09g6b7fg40aeg8ccbgb3cb21c96147")),      # And the dead deserve to be remembered…
          act=1, triggers=["S_CHA_Crypt_SUB_001_f8bc812e-1cb3-46bd-942a-9f572f66ef16"],
          source=G1 + "Act1_Subregions.txt (CHA_Crypt_SUB_001, «CHA_UpperFloor_SUB»)"),
    place("OwlbearNest", "Гнездо медвесыча (детёныш)",
          variant(say("Is that - a baby? Oh no, it's *adorable*. Nobody let me near it.",
                      "Это что… детёныш? О нет, он *прелесть*. Не подпускайте меня к нему.", emo="surprise>happy/2")),
          act=1, triggers=["S_FOR_OwlBear_SUB_1fa871e1-4979-4259-9e5e-5017b06d077f"],
          source=G1 + "Act1_Subregions.txt (FOR_OwlBear_SUB)"),

    # ---------------------------------------------------------------- Акт 2
    # ⭐ Рассвет: момент снятия проклятия (дыхание земли возвращено) или, если он прошёл без неё,
    # флаг «проклятие снято» (ставится позже, при разборе в «Последнем свете» или на входе в INT)
    place("Sunrise", "Рассвет над Оскверненными тенью землями",
          variant(say("Oh. Oh, *look* at it. I'd forgotten the sky could be that colour.",
                      "Ох. Ох, *смотри*. Я забыла, что небо бывает такого цвета.", emo="surprise>happy"),
                  say("Someone should sing. Someone should *always* sing, at a sunrise like this. ...Fine. Me.",
                      "Кто-то должен петь. При таком рассвете *всегда* кто-то должен петь. …Ладно. Я.", emo="happy>happy/2"),
                  say("First sunrise in this place in a hundred years. And I got to see it with you.",
                      "Первый рассвет здесь за сотню лет. И я увидела его с тобой.", emo="happy",
                      note="(берёт героя за руку, не глядя)"), when=[ROMANCE]),
          variant(say("Oh. Oh, *look* at it. I'd forgotten the sky could be that colour.",
                      "Ох. Ох, *смотри*. Я забыла, что небо бывает такого цвета.", emo="surprise>happy"),
                  say("Someone should sing. Someone should *always* sing, at a sunrise like this. ...Fine. Me.",
                      "Кто-то должен петь. При таком рассвете *всегда* кто-то должен петь. …Ладно. Я.", emo="happy>happy/2")),
          act=2, flags=["GLO_LiftingTheCurse_State_BreathHasBeenRestored_2113b54e-a140-4aa0-97ac-219fa7b7d038",
                        "SCL_ShadowCurse_State_CurseLifted_af78af4a-48b2-46a8-be6f-f25dfa579471"],
          source=GD + "Act2_SCE_LiftingTheCurse_HalsinFollowUp.txt:52-68"),
    place("SCLFirst", "Оскверненные тенью земли, первый шаг",
          variant(say("Oh, gods. It's like the whole world is holding its breath. Don't let go of the torch. Or me.",
                      "Ох, боги. Будто весь мир затаил дыхание. Не отпускай факел. И меня.", emo="fear")),
          act=2, levels=["SCL_Main_A"], source="LevelGameplayStarted(\"SCL_Main_A\") — уровень Оскверненных земель"),
    place("LastLight", "Таверна «Последний свет»",
          variant(say("A bubble of light in all that dark. Someone here is *very* stubborn. I like them already.",
                      "Пузырь света посреди такой тьмы. Кто-то здесь *очень* упрямый. Он мне уже нравится.", emo="surprise>happy")),
          act=2, triggers=["S_HAV_Haven_SUB_6ac001f4-9c56-4a1b-963d-a509e158ffab"],
          source=GD + "Act2_Subregions.txt (HAV_Haven_SUB)"),
    place("Gauntlet", "Вызов Шар",
          variant(say("It's beautiful. I hate that it's beautiful.", "Здесь красиво. Ненавижу, что здесь красиво.",
                      emo="surprise>angry")),
          act=2, triggers=["S_SHA_Temple_SUB_348b76ee-33d8-471b-a95d-7ded0d6cdfd5"],
          source=GD + "Act2_Subregions.txt (SHA_Temple_SUB)"),
    place("GauntletLift", "Вызов Шар, подъёмник",
          variant(say("Another lift. At least this one isn't made of goblin rope. ...Is it?",
                      "Ещё один подъёмник. Этот хотя бы не из гоблинской верёвки. …Или?", emo="thinking>fear")),
          act=2, triggers=["S_SHA_Disc_Bounds_ed943df3-d3ca-43e4-890f-4ef9bd30faa1"],
          source=GD + "Act2_SHA_Disc.txt:4 (PROC_TriggerRegisterForPlayers), :69 (EnteredTrigger)"),
    place("Nightsong", "Песня Ночи",
          variant(say("They call her the *Nightsong*. Someone's been keeping a *song* in a cage.",
                      "Её зовут *Песня Ночи*. Кто-то держал *песню* в клетке.", emo="sad>angry")),
          act=2, triggers=["S_SHA_NightsongPrison_SUB_0a302268-dd92-4462-99e5-ca7491815ec0"],
          source=GD + "Act2_Subregions.txt (SHA_Temple_SUB_NightsongPrison)"),
    place("Moonrise", "Лунные Башни",
          variant(say("Moonrise. The name sounds like a ballad. The place looks like the end of one.",
                      "«Лунные Башни». Название — как у баллады. А место — как её финал.", emo="thinking>sad")),
          act=2, triggers=["S_MOO_MoonriseTower_SUB_14187ad9-cf83-44f9-81bf-bb46cb4cd8e6"],
          source=GD + "Act2_Subregions.txt (MOO_MoonriseTower_SUB)"),
    place("Mausoleum", "Величественная усыпальница",
          variant(say("All this stone to remember one family. And the town that paid for it isn't remembered at all.",
                      "Столько камня, чтобы помнить одну семью. А город, который за это заплатил, не помнит никто.",
                      emo="thinking>sad")),
          act=2, triggers=["S_SHA_Mausoleum_SUB_66b74527-67c9-47bf-92a4-b90e1b189739"],
          source=GD + "Act2_Subregions.txt (SHA_Temple_SUB_Mausoleum)"),
    place("HouseOfHealing", "Дом исцеления",
          variant(say("...I'm going to hum. Loudly. Don't mind me.", "…Я буду напевать. Громко. Не обращай внимания.",
                      emo="fear>happy")),
          act=2, triggers=["S_TWN_Hospital_SUB_2ec2cc09-94ab-4479-bacd-cd5ca6911833"],
          source=GD + "Act2_Subregions.txt (TWN_Hospital_SUB)"),

    # ---------------------------------------------------------------- Акт 3
    # ⭐ Первый вид на Врата Балдура: Ривингтон или Драконий перекресток, что раньше
    place("BaldursGateView", "Первый вид на Врата Балдура",
          variant(say("There it is. Baldur's Gate. She never got to see it.", "Вот они. Врата Балдура. Она так их и не увидела.",
                      emo="surprise>sad"),
                  say("I used to dream about this view. I never dreamed someone would be standing next to me.",
                      "Я мечтала об этом виде. Но не мечтала, что рядом кто-то будет стоять.", emo="happy"),
                  when=[ROMANCE]),
          variant(say("There it is. Baldur's Gate. She never got to see it.", "Вот они. Врата Балдура. Она так их и не увидела.",
                      emo="surprise>sad"),
                  say("Thirteen. You remember? You're holding the knife.", "Тринадцатая. Помнишь? Нож держишь ты.",
                      emo="thinking>happy"), when=[NOTCH]),
          variant(say("There it is. Baldur's Gate. She never got to see it.", "Вот они. Врата Балдура. Она так их и не увидела.",
                      emo="surprise>sad")),
          act=3, triggers=["S_WYR_Rivington_SUB_40c3661e-99a1-4189-aa69-c006e77e3db8",
                           "S_WYR_Bridge_SUB_ed5b53be-de5f-46e9-ab78-2707c0bfe61e"],
          source=GD + "Act3_Subregions.txt (WYR_Rivington_SUB, WYR_Bridge_SUB)"),
    place("WyrmsRockBridge", "Змеиная скала, мост",
          variant(say("A bridge older than the city, and a fortress older than the bridge. I need a longer song.",
                      "Мост старше города, а крепость старше моста. Мне нужна песня подлиннее.", emo="surprise>happy")),
          act=3, triggers=["S_WYR_PartyBanter_WyrmsRock_88780113-c3be-43ab-b718-44f72fd16c70"],
          source=GD + "Act3_WYR_General.txt:220 (PROC_RegisterWorldGossipTrigger)"),
    place("GreyHarbour", "Серая бухта, море",
          variant(say("Ships. Real ships. One of them goes to Waterdeep, I bet. ...One day.",
                      "Корабли. Настоящие. Какой-нибудь из них идёт в Глубоководье, спорим. …Когда-нибудь.",
                      emo="surprise>happy>thinking")),
          act=3, triggers=["S_PartyBanterTrigger_NorthDocks_a6b6c79c-48d8-4b7c-a7c5-e0774ada654a",
                           "S_PartyBanterTrigger_SouthDocks_6f047c6b-fbed-49c6-aa51-0936d70fedde"],
          source=GD + "Act3b_LOW_Misc.txt:332,337 (беседы отряда «доки») — [проверить в игре: это Серая бухта]"),
    place("BloomridgePark", "Парк Блумридж",
          variant(say("Grass. Actual grass, in the middle of a city. Can we sit? Just for a verse?",
                      "Трава. Настоящая трава посреди города. Можно посидеть? Хоть один куплет?", emo="surprise>happy")),
          act=3, triggers=["S_PartyBanterTrigger_BloomridgePark_d1289cdd-547d-49da-a538-1ffb117bb5f6"],
          source=GD + "Act3b_LOW_Misc.txt:312 (PROC_RegisterWorldGossipTrigger)"),
    place("Tabernacle", "Киот Штормового берега",
          variant(say("It's so quiet. Like the whole place is listening. Careful what you pray for here.",
                      "Здесь так тихо. Будто всё здание прислушивается. Осторожнее с молитвами.", emo="thinking")),
          act=3, triggers=["S_LOW_StormshoreTabernacle_SUB_8ef5fd83-3fa2-48c1-b103-0846ee138206"],
          source=GD + "Act3b_Subregions.txt (LOW_Stormshore_Tabernacle_SUB)"),
    place("Circus", "Цирк Конца Дней",
          variant(say("A *circus*! Oh, I'm going to be insufferable. You've been warned.",
                      "*Цирк*! Ох, я буду *невыносимой*. Я предупредила.", emo="surprise>happy/2")),
          act=3, triggers=["S_WYR_Circus_SUB_22d3f3ff-3cbb-4240-a3ab-051889832375"],
          source=GD + "Act3_Subregions.txt (WYR_Circus_SUB)"),
    place("SorcerousSundries", "«Волшебные принадлежности»",
          variant(say("So many songbooks. So little coin. This is my own personal Avernus.",
                      "Столько песенников. Так мало денег. Это моё личное Аверно.", emo="happy>sad/1")),
          act=3, triggers=["S_LOW_SorcerousSundries_Shop_SUB_da22d284-7b3a-4c6a-884c-685c07d26068"],
          source=GD + "Act3b_Subregions.txt (LOW_SorcerousSundries_Shop_SUB)"),
    place("SharessCaress", "«Ласка Шаресс»",
          variant(say("Oh. Oh, this is a... *that* sort of place. I'm fine. I'm *completely* fine.",
                      "Ой. Это… *такое* место. Я в порядке. Я *совершенно* в порядке.", emo="surprise>fear>happy"),
                  say("...We are *not* staying the night. ...Are we?", "…Мы тут *не* останемся на ночь. …Или?",
                      emo="happy/2", note="(шёпотом)"), when=[ROMANCE]),
          variant(say("Oh. Oh, this is a... *that* sort of place. I'm fine. I'm *completely* fine.",
                      "Ой. Это… *такое* место. Я в порядке. Я *совершенно* в порядке.", emo="surprise>fear>happy")),
          act=3, triggers=["S_WYR_SharessCaress_SUB_07597ced-f3fe-45f8-bab6-13f0064b75bb"],
          source=GD + "Act3_Subregions.txt (WYR_SharessCaress_SUB)"),
    place("HouseOfHope", "Дом Надежды",
          variant(say("Avernus. It smells like Avernus.", "Аверно. Пахнет Аверно.", emo="fear"),
                  say("My mother - never mind. Let's just get this done.", "Моя мать… неважно. Давай просто закончим с этим.",
                      emo="sad>angry", note="(тихо)")),
          act=3, triggers=["S_LOW_HouseOfHope_SUB_49462249-7f39-4b91-af1d-ba121c711213"],
          source=GD + "Act3b_Subregions.txt (LOW_HouseOfHope_SUB)"),
    place("MorphicPool", "Водоем Изменений",
          variant(say("It's gorgeous. Everything here that's gorgeous wants to kill us. That's a pattern.",
                      "Красиво. Всё красивое здесь хочет нас убить. Прослеживается закономерность.", emo="surprise>thinking")),
          act=3, triggers=["S_END_MorphicPool_SUB_5a646d13-e9bb-42f0-84e6-1f8fad2bef81"],
          source=GD + "Act3c_Subregions.txt (END_MorphicPool_SUB)"),
    place("AstralPlane", "Астральный план",
          variant(say("No up, no down, just stars - *everywhere*. She'd dance right off the edge.",
                      "Ни верха, ни низа, только звёзды — *повсюду*. Она бы сплясала прямо за край.", emo="surprise>happy")),
          act=3, triggers=["S_END_AstralPrism_SUB_adf44e33-ae27-4186-aff7-84d61dbedcae",
                           "S_INT_AstralPlane_SUB_98791ae8-8cac-489f-8451-9f1a3d85cb19"],
          source=GD + "Act3c_Subregions.txt (END_AstralPrism_SUB), Act2b_Subregions.txt (INT_AstralPlane_SUB)"),
]

# Места без надёжного запуска в данных игры: в игру не идут, реплики остаются в сценарии.
GAPS = [
    ("SeluneOutpost", "Селунитский аванпост (Подземье)",
     "нет подрегиона и триггера бесед с этим местом; точечные триггеры путевых камней Подземья "
     "(_Gustav_Waypoints_Act1.txt) не подписаны местом — не угадываем"),
    ("GrymforgeLift", "Лифт Гримфорджа",
     "лифт S_UND_Elevator_Fort_ToShadowlands — предмет перехода в акт 2 (Act1_UND_DuergarCamp_Elevator.txt:188): "
     "по нажатию начинается смена уровня, реплика не успеет; своего триггера у кабины нет"),
    ("ClearNight", "Ясная ночь в пути",
     "в данных нет события «ясная ночь»: смена дня и ночи есть только в лагере (GLO_CAMP_State_NightMode)"),
    ("WaukeensRest", "Приют Вокин (горит)",
     "триггер горящего трактира S_PLA_TavernInvestigation_BurnDownTrigger_Inner игра снимает с отряда "
     "(Act1_PLA_TavernInvestigation.txt:711), подрегиона у трактира нет"),
    ("Reithwin", "Рейтвин",
     "у города нет подрегиона; триггеры бесед Рейтвина — только «…Cleared» (после зачистки, Act2_Gossip.txt:15-21)"),
]
